# Generated by Django 5.0.1 on 2024-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
