# Generated by Django 5.0.1 on 2024-02-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_product_is_new_product_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
    ]
