version: "3.8"

services:
  backend_service:
    build: .
#    image: backend_image
#    container_name: compose_backend_container
#    command: python3 manage.py runserver 8000
    env_file: .env
    restart: always
    ports:
      - '8005:8000'

  postgres_service:
    image: postgres:alpine
#    container_name: compose_postgres_container
    ports:
      - '5432:5432'
    env_file: .env
#    environment:
#      - POSTGRES_PASSWORD=1
