version: "3.8"

services:
  backend:
    build:
      context: ./
    command: python3 manage.py runserver 8000
    ports:
      - '8000:8000'

  postgres:
    image: postgres:alpine
    container_name: postgres_container
    ports:
      - '5430:5432'
    environment:
      - POSTGRES_PASSWORD=1