version: "3.8"

services:
  backend_service:
    build: .
    #    image: backend_image
    #    container_name: compose_backend_container
    #    command: python3 manage.py runserver 8000
    env_file: .env
    ports:
      - '8005:8000'

  postgres-service:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - pg_data_service:/var/lib/postgresql/data
    env_file: .env

  minio-service:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    env_file: .env
    command: server --console-address ":9001" /data

volumes:
  minio_storage:
  pg_data_service: